version: '3'
services:
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=trash
  odoo:
    image: "odoo:latest"
    depends_on:
      - db
    ports:
      - "8069:8069"
    links:
      - "db"
